### PR TITLE
Rspec Testing for Enumerable Methods

### PR DESCRIPTION
**Pull request by acushlakoncept**
In this pull request, I and my partner have successfully implemented and tested all the possible contexts for our custom enumerable methods listed below using Rspec. 
- #my_each
- #my_each_with_index
- #my_select
- #my_all?
- #my_any?
- #my_none?
- #my_count
- #my_map
- #my_inject
- #multiply_els

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi **`Team`**, you have done a great job with this project. :100: Git flow :100: PR :100: README :+1: We just need to implement the negative test cases so we can approve this project :slightly_smiling_face: 
- Kindly add a negative scenario for all the methods tested
- We currently have 3 authors to this project, could you explain why or remove the extra author in the README

Kindly implement this and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by lekegitrepo** [comment]
#### Good job, for implementing the required changes :+1:
#### This project is approved.

#### _Reviewed by Temitayo Adeleke_.

**Review by lekegitrepo — APPROVED** [review]
##### Status: Approve

**Pull request merged**
