### PR TITLE
Recreated Enumerable Methods

### PR DESCRIPTION
**Pull request by acushlakoncept**
In this project, I and my partner have recreated our own versions of enumerable methods and tested them as well. The recreated methods as thus:
- `#my_each`
- `#my_each_with_index`
- `#my_select`
- `#my_all?`
- `#my_any?`
- `#my_none?`
- `#my_count`
- `#my_map`
- `#my_inject`

And lastly - `multiply_els` which multiplies all the elements of the array together by using #my_inject

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work! @acushlakoncept and @jacobrees 
Please check on this in a few minutes for some feedback

**Comment by nikasulo** [comment]
screenshot
screenshot
screenshot
screenshot
screenshot
screenshot
screenshot

**Comment by nikasulo** [comment]
@acushlakoncept and @jacobrees I went on to attach the failing tests on your project, so you can see and correct the issues. Please consider them, make the necessary changes and request another review. I wish you the very best and see you at the top 🚀

**Comment by acushlakoncept** [comment]
> @acushlakoncept and @jacobrees I went on to attach the failing tests on your project, so you can see and correct the issues. Please consider them, make the necessary changes and request another review. I wish you the very best and see you at the top 🚀

Hi @Oluwadamilareolusakin,
Please could break down, the issues to us, this is our first time in Ruby. The error messages do not really help us much, don't even know where to start.

Thank you.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI @acushlakoncept, @jacobrees :clap:, There is still work to do on your methods:**

1. **my_each and my_each_with_index** should return the given enumerable after calling the given block for each element. So if my_each is called on an array or a range, after calling the block for all elements in the collection it should return the original array or range. Adding a return self after the loop in both methods should take care of this.

2. When no block or argument is given **my_all?** should return true when all the elements in the enum and truthy values and return false if at least one element in the collection is a falsy value.
example `[1, 2, 3].my_all?` should return `true` and `[nil, 1, 2, 3].my_all?` should return `false`.

3. **my_all?** should be able to receive an **optional argument**. If the argument is a class, then it should return true if all members of the given enumerable are members of that class, otherwise it should return false. If the argument is a regex, then it should return true if all members of the enumerable matches the regex, otherwise it should return false. If the argument is any other pattern besides a class or regex, a similar logic holds.
Example
```ruby
[1, 2, 3].my_all?(Integer) should return true
[1, 2, "a"].my_all?(Integer) should return false
['dog', 'door'].my_all?(/d/) should return true
['dog', 'door', 'ant'].my_all?(/d/) should return false
[2, 2, 2].my_all?(2) should return true
[1, 2, 3].my_all?(2) should return false
```

4. When no block or argument is given to **my_any?** it should return true if there is at least one element in the given enumerable that is a truthy, otherwise, it should return false.
example `[1, 2, false].my_any?` should return `true` and `[nil, false nil].my_any?` should return `false`.

5.  **my_any?** should be able to receive an **optional argument**. If the argument is a class, then it should return true if there is at least one member of the given enumerable that is a member of that class, otherwise it should return false. If the argument is a regex, then it should return true if there is at least one member of the enumerable that matches the regex, otherwise it should return false. If the argument is any other pattern besides a class or regex, a similar logic holds.
Example
```ruby
[1, 2, "a"].my_any?(Integer) should return true
["a",  "b",  "a"].my_any?(Integer) should return false
['dog', 'door', 'ant'].my_any?(/d/) should return true
['hey', 'book', 'ant'].my_any?(/d/) should return false
[2, 2, 3].my_any?(2) should return true
[1, 3, 3].my_any?(2) should return false
```

6.  When no block or argument is given to **my_none?,** it should return true if **there is no** element in the given enumerable that is a truthy, otherwise, it should return false.
example `[nil, nil, false].my_none?` should return `true` and `[1, 2, 3].my_none?` should return `false`.

7. **my_none?** should be able to receive an **optional argument**. If the argument is a class, then it should return true if there is no member of the given enumerable that is a member of that class, otherwise it should return false. If the argument is a regex, then it should return true if there is no member of the enumerable that matches the regex, otherwise it should return false. If the argument is any other pattern besides a class or regex, a similar logic holds.
Example
```ruby
["a", "b", "a"].my_none?(Integer) should return true
["1",  "2",  "a"].my_none?(Integer) should return false
['rot', 'not', 'ant'].my_none?(/d/) should return true
['door', 'dog', 'ant'].my_none?(/d/) should return false
[1, 3, 3].my_none?(2) should return true
[1, 2, 3].my_none?(2) should return false
```

8. Please read [this article](https://medium.com/@terrancekoar/inject-method-explained-ed531eff9af8) to understand how the **inject** method behaves and compare the behaviour with your own **my_inject** method.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by acushlakoncept** [comment]
Thank you @mosesogwo for the detailed review, this has helped a whole lot.
We will work on it.

**Comment by lekegitrepo** [comment]
#### Hi @acushlakoncept and @jacobrees :clap: :clap:
##### Good job. This project is approved. However, you should create another file for the test and remove all the tests from the main.rb file.

#### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved

**Pull request merged**
